version: '2'
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: keeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:3"
      KAFKA_ADVERTISED_LISTENERS: plaintext://broker:9092
  log:
    image: log
    build: ../
    container_name: log
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8090:8080"
    command: ["java","-jar","/app.jar"]
