version: '3.6'
volumes:
  shared-workspace:
    name: hadoop-distributed-file-system
    driver: local
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: keeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CREATE_TOPICS: 'test_topic:1:1'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092'
  log:
    image: log
    build: ../
    container_name: log
    depends_on:
      - zookeeper
      - kafka
    ports:
      - '8090:8080'
    command:
      - java
      - '-jar'
      - /app.jar
  jupyterlab:
    image: 'andreper/jupyterlab:2.1.4-spark-3.0.0'
    container_name: jupyterlab
    ports:
      - '8888:8888'
      - '4040:4040'
    volumes:
      - './data:/data/'
  spark-master:
    image: 'andreper/spark-master:3.0.0'
    container_name: spark-master
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - './data:/data/'
  spark-worker-1:
    image: 'andreper/spark-worker:3.0.0'
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - '8081:8081'
    volumes:
      - './data:/data/'
    depends_on:
      - spark-master
  spark-worker-2:
    image: 'andreper/spark-worker:3.0.0'
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - '8082:8081'
    volumes:
      - './data:/data/'
    depends_on:
      - spark-master